import { Check, MapPin, Moon, Monitor, Sun } from 'lucide-react'
import { useAppDispatch, useAppSelector } from '../../app/hooks'
import { setTheme } from '../ui/uiSlice'
import { user } from '../../constants/mockData'
import type { ThemeMode } from '../../types'
import { PageHeader } from '../../components/ui/PageHeader'

export function ProfilePage() {
  const dispatch = useAppDispatch()
  const theme = useAppSelector((state) => state.ui.theme)
  const options: { mode: ThemeMode; label: string; icon: typeof Sun }[] = [{ mode: 'light', label: 'Light', icon: Sun }, { mode: 'dark', label: 'Dark', icon: Moon }, { mode: 'system', label: 'System', icon: Monitor }]
  return <div className="mx-auto max-w-4xl"><PageHeader eyebrow="Account" title="Profile" description="Manage your personal details and preferences." /><div className="grid gap-6 md:grid-cols-[0.8fr_1.2fr]"><section className="rounded-2xl bg-slate-900 p-6 text-white"><div className="grid size-20 place-items-center rounded-full bg-amber-200 text-xl font-bold text-slate-900">{user.initials}</div><h2 className="mt-5 font-display text-2xl font-semibold">{user.name}</h2><p className="mt-1 text-sm text-slate-400">{user.role}</p><div className="mt-8 space-y-3 border-t border-slate-700 pt-5 text-sm text-slate-300"><p>{user.email}</p><p className="flex items-center gap-2"><MapPin size={15} />{user.location}</p><p>Member since {user.joined}</p></div></section><div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-display text-lg font-semibold dark:text-white">Personal information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Full name" value={user.name} /><Field label="Email address" value={user.email} /><Field label="Location" value={user.location} /><Field label="Account type" value={user.role} /></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-display text-lg font-semibold dark:text-white">Appearance</h2><p className="mt-1 text-sm text-slate-500">Choose how Ledgerly looks for you.</p><div className="mt-5 grid grid-cols-3 gap-2">{options.map(({ mode, label, icon: Icon }) => <button key={mode} type="button" onClick={() => dispatch(setTheme(mode))} className={`relative flex flex-col items-center gap-2 rounded-xl border px-3 py-4 text-sm font-medium transition ${theme === mode ? 'border-amber-300 bg-amber-50 text-amber-800 dark:bg-amber-300/10 dark:text-amber-200' : 'border-slate-200 text-slate-500 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800'}`}><Icon size={18} />{label}{theme === mode && <Check className="absolute right-2 top-2 text-amber-600" size={14} />}</button>)}</div></section></div></div></div>
}
interface FieldProps { readonly label: string; readonly value: string }
function Field({ label, value }: Readonly<FieldProps>) { return <div><p className="mb-1 text-xs font-medium text-slate-400">{label}</p><div className="rounded-lg bg-slate-50 px-3 py-2.5 text-sm text-slate-700 dark:bg-slate-800 dark:text-slate-200">{value}</div></div> }
